"""
Python script for merging latex feedback with script to mark.
Make backups.

Usage:
Get a list of students from the files in the dir - python(3) merger.py 2
Copy the template for every student - python(3) merger.py 0
Do the marking in all of the latex files
Merge everything and put into the complete dir   - python(3) merger.py 1
"""

import os
import sys
import csv

if len(sys.argv) !=2:
    print("Usage: python(3) merger.py <mode>")
    exit()

mode=int(sys.argv[1])

if mode ==0:
    #For every name in the folder (generated by mode 2) create a tex file
    #based off of the template in template/ directory. This may take a 
    #second.
    with open('names.csv', newline='') as f:
        reader = csv.reader(f)
        namelist = list(reader)
    for name in namelist[0]:
        if name != "": #Weird artefact
            os.system("cp template/handin1_template.tex " +name+ "_mark.tex")
            os.system("pdflatex " + name + "_mark.tex" )

elif mode ==1:
    #Merge all the scripts with the feedback files.
    with open('names.csv', newline='') as f:
        reader = csv.reader(f)
        namelist = list(reader)
    for name in namelist[0]:
        if name != "": #Weird artefact
            outstr = "pdftk "
            outstr += name + "_mark.pdf "
            outstr += name + ".pdf "
            outstr += "output "
            outname = name + "_full.pdf"
            outstr += "complete/" + outname
            os.system(outstr)

elif mode ==2:   
    #Generates a csv file of all of the students names.
    names = [".".join(f.split(".")[:-1]) for f in os.listdir()\
             if os.path.isfile(f)]
    names.remove("merger")
    namefile = open("names.csv","w")
    for name in names:
        namefile.write(name + ",")
    namefile.close
    os.system("mkdir complete")

